<?php
	header("Access-Control-Allow-Origin: *");	

echo'LYCEE ALBERT CAMUS - 92270 BOIS COLOMBES$LYCEE DESCARTES - 92160 ANTHONY$CUISINE BRETAGNE - 78955 CARRIERES SOUS POISSY$LYCEE PAUL LAPIE - 92400 COURBEVOIS';

?>